### ISSUE TITLE
FrontMatter::get() should return $this->data rather than entire object if called without $key

### ISSUE THREAD

**Issue by rgasch** [hydephp/develop#1157]
From previous chat: 

```
    public function get(string $key = null, mixed $default = null): mixed
    {
        if ($key) {
            return Arr::get($this->data, $key, $default);
        }

        return $this;
    }
```

Since get is accessing data items, it would make sense to return the entire data array if it's called without $key ... if we return the entire object (ie: $this) then we're really mixing semantics and things could get confusing when using this code down the line (I'm facing this confusion right now with my log parser script).

**Comment by caendesilva** [comment]
Thanks for the report! As stated in DMs, noting here for reference, I agree that this is a bug. I just need to make sure there are no side effects caused by this. I will see if I can fix it today.
