### ISSUE TITLE
Add configuration option to allow more file types in the _media directory

### ISSUE THREAD

**Issue by emmadesilva** [hydephp/develop#39]
As Hyde strives to be safe by default, currently the glob pattern for `_media` file transfers is set to "safe" files. However, it would be nice to have the config option to expand on this.

**Comment by caendesilva** [comment]
Implemented. You can now specify comma separated values in the config.

Here are the defaults:
```php
config('hyde.media_extensions', 'png,svg,jpg,jpeg,gif,ico,css,js'))
```

Here is how the glob pattern is now loaded in the CollectionService for reference:

```php
return glob(Hyde::path('_media/*.{'.str_replace(' ', '',
    config('hyde.media_extensions', 'png,svg,jpg,jpeg,gif,ico,css,js')).'}'), GLOB_BRACE
);
```
