### ISSUE TITLE
Rename ViewDiffService class to ChecksumService or HashService

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#552]
I can never remember the name of the ViewDiffService class, and propose it be renamed. Using a more generic name such as "ChecksumService" or "HashService" would make it easier to remember, and open the service up to uses outside of Blade views, such as when using the EOL agnostic MD5 hash methods.

I'm creating this as an issue for Hacktoberfest as I think it's a fairly easy task. If you are interested in taking this on, here are some tips on getting started:

1. Read the [Hacktoberfest rules](https://hacktoberfest.com/participation/).
2. Decide a new name for the service. I'm suggesting ChecksumService or HashService. Pick one of those, or come up with an even better one!
3. Rename the class, and all references to it.
4. Update the RELEASE_NOTES.md file as it's a breaking change.
5. Create a pull request!

Good luck, and let me know if you have any questions!

**Comment by ManasviGoyal** [comment]
I would like to work on this

**Comment by caendesilva** [comment]
> I would like to work on this

Awesome! Go for it! Let me know if you need any guidance.

**Comment by ManasviGoyal** [comment]
I found it being used in a PHP file and a test. Are there any other instances?

**Comment by caendesilva** [comment]
> I found it being used in a PHP file and a test. Are there any other instances?

It's used in a few places. If you are using VSCode, you can find them all by [searching across files (Shift+CTRL+F)](https://code.visualstudio.com/docs/editor/codebasics#_search-across-files)

![image](https://user-images.githubusercontent.com/95144705/193468449-48eebe5c-6fea-42a6-98d5-46ee1fbd7e71.png)
