### ISSUE TITLE
Fix test that is in the wrong namespace

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#557]
I noticed that the test [`NavigationDataTest.php`](https://github.com/hydephp/develop/blob/master/packages/framework/tests/Models/NavigationDataTest.php) is in the wrong namespace. This could be a quick and easy contribution that's great for beginners in Hacktoberfest!

What you need to do is the following:
1. Move the test from `framework/tests/Models` to `framework/tests/Feature`
2. Update the namespace accordingly
3. Submit a pull request to this repository

Let me know if you need any help! Good luck!

**Comment by chikaldirick** [comment]
Hey! I've just added requested changes within https://github.com/hydephp/develop/pull/558
The test is now in a proper directly with a respective namespace.

**Comment by caendesilva** [comment]
> Hey! I've just added requested changes within #558 The test is now in a proper directly with a respective namespace.

Wow, that was fast! Just approved the workflow, will merge once it passes. Thank you!
