### ISSUE TITLE
The File.php model's getMimeType() helper function should support XML in the lookup table

### ISSUE THREAD

**Issue by emmadesilva** [hydephp/develop#562]
Here's another easy Hacktoberfest bug to fix!

Since this is targeted at beginners and I want you to learn something, I won't tell you exactly what value it should return, however I am happy to offer help if you need it.

Your mission, should you choose to accept it, is to find out the proper mime type for XML files, then submit a pull request to this repository, adding the mime type mapping to the `$lookup` array in the `getMimeType()` method of the `File.php` class.

Good luck!

**Comment by LunarMarathon** [comment]
Hey, I would like to try this! 
I'm not sure if you'll be assigning first but since you've mentioned to submit a PR, I'll make the changes and submit one

**Comment by caendesilva** [comment]
> Hey, I would like to try this! I'm not sure if you'll be assigning first but since you've mentioned to submit a PR, I'll make the changes and submit one

Hey! Go right ahead! I don't usually assign people, but it's great that you left a comment, so other people knows that you are working on it.

Good luck and let me know if you need any help! But most importantly: have fun!

**Comment by caendesilva** [comment]
Fixed by https://github.com/hydephp/develop/pull/563
